Fix argument parsing when there is no extra options

diff --git a/bin/capture b/bin/capture
--- a/bin/capture
+++ b/bin/capture
@@ -2,15 +2,14 @@
 out=/feedback/out
 err=/feedback/err
 user=nobody
-while [ -z "${1%%-*}" ]; do
+while [ "$1" ]; do
     case "$1" in
         -o) out=$2 ; shift 2 ;;
         -e) err=$2 ; shift 2 ;;
         -u) user=$2 ; shift 2 ;;
         --) shift ; break ;;
-        *) echo "Invalid option '$1' for $0" >&2
-           exit 64
-           ;;
+        -*) echo "ERROR: Invalid option '$1' for $0" >&2 ; exit 64 ;;
+        *) break ;;
     esac
 done
 
diff --git a/bin/pre b/bin/pre
--- a/bin/pre
+++ b/bin/pre
@@ -2,13 +2,12 @@
 TMP_FILE=/tmp/preout
 
 class=""
-while [ -z "${1%%-*}" ]; do
+while [ "$1" ]; do
     case "$1" in
         -c) class="$class${class:+ }$2" ; shift 2 ;;
         --) shift ; break ;;
-        *) echo "Invalid option '$1' for $0" >&2
-           exit 64
-           ;;
+        -*) echo "ERROR: Invalid option '$1' for $0" >&2 ; exit 64 ;;
+        *) break ;;
     esac
 done
 
diff --git a/bin/stdio-diff b/bin/stdio-diff
--- a/bin/stdio-diff
+++ b/bin/stdio-diff
@@ -5,7 +5,7 @@ space=""
 allspace=""
 pass="ok"
 fail=""
-while [ -z "${1%%-*}" ]; do
+while [ "$1" ]; do
     case "$1" in
         -c) case="x" ; shift ;;
         -s) space="x" ; shift ;;
@@ -14,9 +14,8 @@ while [ -z "${1%%-*}" ]; do
         -P) pass="" ; shift ;;
         -f) fail="$2" ; shift 2 ;;
         --) shift ; break ;;
-        *) echo "Invalid option '$1' for $0" >&2
-           exit 1
-           ;;
+        -*) echo "ERROR: Invalid option '$1' for $0" >&2 ; exit 64 ;;
+        *) break ;;
     esac
 done
 
diff --git a/bin/title b/bin/title
--- a/bin/title
+++ b/bin/title
@@ -3,14 +3,14 @@
 element="h1"
 class=""
 stdout=""
-while [ -z "${1%%-*}" ]; do
+while [ "$1" ]; do
     case "$1" in
         -c) class="$class${class:+ }$2" ; shift 2 ;;
         -e) element="$2" ; shift 2 ;;
         -O) stdout="x" ; shift 1 ;;
-        *) echo "Invalid option '$1' for $0" >&2
-           exit 64
-           ;;
+        --) shift ; break ;;
+        -*) echo "ERROR: Invalid option '$1' for $0" >&2 ; exit 64 ;;
+        *) break ;;
     esac
 done
 
