Rewrite scripts for dash with staff only errors

diff --git a/bin/capture b/bin/capture
--- a/bin/capture
+++ b/bin/capture
@@ -1,8 +1,27 @@
-#!/bin/bash
-OUT_FILE=/feedback/out
-ERR_FILE=/feedback/err
-chown -R nobody . >> $ERR_FILE 2>&1
-(sudo -u nobody ${@:1}) >> $OUT_FILE 2>>$ERR_FILE
+#!/bin/sh
+exec 2>> /feedback/errors
+
+out=/feedback/out
+err=/feedback/err
+user=nobody
+while [ -z "${1%%-*}" ]; do
+    case "$1" in
+        -d) out=$2/out ; err=$2/err ; shift 2 ;;
+        -o) out=$2 ; shift 2 ;;
+        -e) err=$2 ; shift 2 ;;
+        -u) user=$2 ; shift 2 ;;
+        --) shift ; break ;;
+        *) echo "Invalid option '$1' for $0" >&2
+           exit 64
+           ;;
+    esac
+done
+
+chown -R $user . >&2
+USER=$user HOME=/tmp PATH=/usr/local/bin:/usr/bin:/bin \
+    env -u REC -u SID -- \
+    chpst -u $user -- \
+    "$@" >> "$out" 2>> "$err"
 RES=$?
-chown -R root . >> $ERR_FILE 2>&1
+chown -R root . >&2
 exit $RES
diff --git a/bin/pre b/bin/pre
--- a/bin/pre
+++ b/bin/pre
@@ -1,11 +1,19 @@
-#!/bin/bash
-TMP_FILE=preprepreprepreprepretmp
-${@:1} > $TMP_FILE
+#!/bin/sh
+TMP_FILE=/tmp/preout
+
+class=""
+while [ -z "${1%%-*}" ]; do
+    case "$1" in
+        -c) class="$class${class:+ }$2" ; shift 2 ;;
+        --) shift ; break ;;
+        *) echo "Invalid option '$1' for $0" >&2
+           exit 64
+           ;;
+    esac
+done
+
+"$@" > $TMP_FILE
 RES=$?
-if [ -s $TMP_FILE ]; then
-  echo "<pre>"
-  cat $TMP_FILE | sed 's/\&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g'
-  echo "</pre>"
-fi
-rm $TMP_FILE
+[ -s $TMP_FILE ] && _prewrap "$class" < $TMP_FILE
+rm $TMP_FILE || true
 exit $RES
