Fix git problems

diff --git a/bin/git-clone-submission b/bin/git-clone-submission
--- a/bin/git-clone-submission
+++ b/bin/git-clone-submission
@@ -18,16 +18,25 @@ SOURCE=$(cat $READ)
 mv $READ .
 
 # Clone the repository.
+mkdir -p /root/.ssh
+cp $1 /root/.ssh/id_rsa
+ssh -T -o "StrictHostKeyChecking no" git@version.aalto.fi > /dev/null 2&>1
 mkdir -p $DIR
 cd $DIR
-ssh-agent bash -c 'ssh-add $1; git clone $SOURCE .'
+git clone $SOURCE .
 res=$?
+rm -rf /root/.ssh
 if [ $res -eq 0 ]
 then
 	echo "Finished successfully - HEAD:"
 	git rev-parse HEAD
 else
-	echo "Failed to clone \"$SOURCE\"." >&2
+	echo ""
+	echo "Specifically,"
+	echo "1. Add given deploy key to your project"
+	echo "2. Enter exact repository URL"
+	echo ""
+	echo "Failed to clone: $SOURCE" >&2
 	exit $res
 fi
 cd ..
