Rewrite pre with an anonymous pipe
This removes a shared temporary file

diff --git a/bin/pre b/bin/pre
--- a/bin/pre
+++ b/bin/pre
@@ -1,5 +1,4 @@
 #!/bin/sh
-TMP_FILE=/tmp/preout
 
 class=""
 while [ "$1" ]; do
@@ -11,8 +10,24 @@ while [ "$1" ]; do
     esac
 done
 
-"$@" > $TMP_FILE
-RES=$?
-[ -s $TMP_FILE ] && _prewrap "$class" < $TMP_FILE
-rm $TMP_FILE || true
-exit $RES
+[ "$class" ] && class=" class=\"$class\""
+
+wrap() {
+    sed -e "1 i <pre${class}>" -e '$a</pre>' \
+        -e 's/\&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g'
+}
+
+if [ $# -gt 0 ]; then
+    # this equals to `"$@" | wrap`, but exit code ($?) comes from "$@" instead of `wrap`
+    # fd 4 contains stdout from the piped command
+    # fd 3 contains the exit code from "$@"
+    # fd 2 is passed through as is
+    # fd 1 is passed via | character
+    #  - between "$@" and `wrap`
+    #  - between groups, i.e., from fd 3 to second group (read xs; exit)
+    #  - between this line and this script, i.e., from fd 4 to this script
+    { { { { "$@" 3>&- 4>&-; echo $? >&3; } | wrap >&4; } 3>&1; } | { read xs; exit $xs; }; } 4>&1
+    exit $?
+else
+    wrap
+fi
